---
title: "Reproducible Research"
subtitle: "Concepts and Tools"
format: 
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    editor: visual
---

## Agenda and Goals

-   Project and data organization principles

-   Writing more reusable code

-   A quick tour of tools

-   Playing with Git

-   Data sharing

    ::: aside
    With lots of examples from our lab
    :::

## What do we mean by Reproducible Research?

## Who is this for?

# Project Organization and Data Management

## *Good enough practices in scientific computing*

## Checking in on your data stewardship

# Version control with *`git`*

## Motivation for using git

::: {style="text-align: center; margin-top: 2em"}
*"yourself from 3 months ago doesn't answer email"*
:::

## Git in RStudio

[Happy Git and and GitHub for the useR](https://happygitwithr.com/)

## Interactive exercise with RStudio Cloud

## Working toward a reproducible toolkit

# Examples from our lab

## Analysis of public COVID-19 datasets

-   Complex analysis integrating multiple public data sources

-   Sharing the code plus output increases transparency

::: {style="text-align: center; margin-top: 1em"}
[*Nature Comms* - Rendered markdown with code and output](https://justlab.github.io/COVID_19_admin_disparities/code/NYC_COVID_Disparities.html){preview-link="true" style="text-align: center"}
:::

::: footer
Publication: [Carrión, D., et al. (2021). Neighborhood-level disparities and subway utilization during the COVID-19 pandemic in New York City. *Nature Communications*, 12(1).](https://doi.org/10.1038/s41467-021-24088-7)
:::

## Reproducible simulation

::: {style="text-align: center; margin-top: 2em"}
[Code repository with targets workflow](https://github.com/justlab/casecrossover_preterm_simulation){style="text-align: center"}
:::

::: footer
Publication: [Carrión, D., et al. (2022). The Case--Crossover Design Under Changing Baseline Outcome Risk: A Simulation of Ambient Temperature and Preterm Birth. *Epidemiology*.](https://doi.org/10.1097/EDE.0000000000001477)
:::

## Analysis of data from NIH repositories

::: {style="text-align: center; margin-top: 2em"}
[Zenodo repository for code: DOI 10.5281/zenodo.1172730](https://doi.org/10.5281/zenodo.1172730){style="text-align: center"}
:::

::: footer
Publication: [Heiss, J., Just, A. 2018. Identifying mislabeled and contaminated DNA methylation microarray data: an extended quality control toolset with examples from GEO. *Clin Epigenet*.](https://doi.org/10.1186/s13148-018-0504-1)
:::

# Data sharing

## FAIR principles and data sharing expectations

::: incremental
-   **F**indability
-   **A**ccessibility
-   **I**nteroperability
-   **R**euse of digital assets
:::

## New NIH rules coming Jan 25, 2023

[sharing.nih.gov](https://sharing.nih.gov/)

## Publishing reproducible research

## Questions?

email: `allan.just@mssm.edu`

References:

-   Wilson G, Bryan J, Cranston K, Kitzes J, Nederbragt L, Teal TK (2017) Good enough practices in scientific computing. PLoS Comput Biol 13(6): e1005510. <https://doi.org/10.1371/journal.pcbi.1005510>
